"""
src/voice_pipeline.py — Real-time Voice Pipeline cho Orange Pi 5

PURPOSE:
    Pipeline giọng nói thời gian thực chạy trên Orange Pi 5:
    Mic (es8388) → STT → RAG Engine → TTS → Speaker (es8388)

    Hỗ trợ 2 chế độ chạy:
    1. Interactive text mode: Test RAG pipeline không cần mic
    2. Full voice mode: Pipeline giọng nói đầy đủ qua AudioTransport

ARCHITECTURE DECISIONS:
    - AudioTransport quản lý phần cứng âm thanh (PyAudio/ALSA)
    - SileroVAD qua Faster-Whisper cho voice activity detection
    - Streaming TTS tại ranh giới câu (giảm latency)
    - Session-based conversation memory (3-turn sliding window)
    - Hỗ trợ cả online (Google STT) và offline (Whisper) mode
"""

import asyncio
import os
import sys
import time
from pathlib import Path
from typing import Optional

from loguru import logger

from src.config import get_settings, setup_logging
from src.conversation_memory import ConversationMemory
from src.rag_engine import RAGEngine
from src.stt_service import STTService
from src.tts_service import TTSService
from src.audio_transport import AudioTransport
from src.utils import Timer, get_memory_usage_mb


class VoicePipeline:
    """
    Main voice conversation pipeline for Mầm Nhỏ.

    This is the top-level orchestrator that connects all services:
    - AudioTransport: Hardware audio I/O (es8388 / hw:2,0)
    - STT: Faster-Whisper (Vietnamese speech → text)
    - RAG: Intent classification + ChromaDB + Qwen 7B
    - TTS: Piper (text → Vietnamese speech)

    The pipeline supports:
    - Barge-in: User can interrupt the bot mid-speech
    - Streaming: TTS starts before LLM finishes generating
    - Safety: Emergency override with hardcoded messages
    """

    def __init__(self):
        self._settings = get_settings()
        self._stt = STTService()
        self._tts = TTSService()
        self._rag = RAGEngine()
        self._memory = ConversationMemory()
        self._audio = AudioTransport()
        self._trimester: Optional[int] = None

    def set_trimester(self, trimester: int) -> None:
        """
        Set the current pregnancy trimester for filtered retrieval.

        Args:
            trimester: 1, 2, or 3 (0 = unspecified)
        """
        if trimester in (0, 1, 2, 3):
            self._trimester = trimester
            logger.info(f"Trimester set to {trimester}")

    def reset_session(self) -> None:
        """Reset conversation memory for a new session."""
        self._memory.clear()
        logger.info("Session reset — memory cleared")

    async def process_audio_turn(
        self,
        audio_path: str,
        kick_data: Optional[str] = None,
    ) -> bytes:
        """
        Process a single conversation turn from audio file.

        Full pipeline: Audio → STT → RAG → TTS → Audio

        Args:
            audio_path: Path to user's audio recording
            kick_data: Optional kick counter data to inject

        Returns:
            WAV audio bytes of the assistant's response
        """
        mem_before = get_memory_usage_mb()
        logger.info(f"Processing turn | RAM: {mem_before:.1f}MB")

        # Step 1: Speech-to-Text
        with Timer("Full STT", log_level="INFO"):
            user_text = self._stt.transcribe(audio_path)

        if not user_text.strip():
            logger.warning("STT returned empty text, skipping")
            return self._tts.synthesize(
                "Dạ, em không nghe rõ, Mẹ nói lại giúp em nhé."
            )

        # Step 2: RAG Processing (Intent + Retrieval + Generation)
        with Timer("Full RAG pipeline", log_level="INFO"):
            response, safety = self._rag.process_query(
                user_input=user_text,
                memory=self._memory,
                trimester=self._trimester,
            )

        # Step 3: Text-to-Speech
        with Timer("Full TTS", log_level="INFO"):
            audio_response = self._tts.synthesize(response)

        mem_after = get_memory_usage_mb()
        logger.info(
            f"Turn complete | RAM: {mem_after:.1f}MB "
            f"(Δ{mem_after - mem_before:+.1f}MB) | "
            f"emergency={safety.is_emergency}"
        )

        return audio_response

    async def process_audio_turn_stream(
        self,
        audio_path: str,
        audio_callback=None,
        kick_data: Optional[str] = None,
    ):
        """
        Streaming version — yields audio chunks in real-time.

        Used with the pipecat framework for immediate playback.
        TTS starts producing audio as soon as the first sentence
        is generated by Qwen 7B.

        Args:
            audio_path: Path to user's audio recording
            audio_callback: Async callback to send audio chunks
            kick_data: Optional kick counter data
        """
        # Step 1: STT
        user_text = self._stt.transcribe(audio_path)

        if not user_text.strip():
            audio = self._tts.synthesize(
                "Dạ, em không nghe rõ, Mẹ nói lại giúp em nhé."
            )
            if audio_callback:
                await audio_callback(audio)
            return

        # Step 2 + 3: Streaming RAG → TTS
        text_stream = self._rag.process_query_stream(
            user_input=user_text,
            memory=self._memory,
            trimester=self._trimester,
        )

        for audio_chunk in self._tts.synthesize_stream(text_stream):
            if audio_callback:
                await audio_callback(audio_chunk)

    def run_voice_loop(self) -> None:
        """
        Vòng lặp giọng nói thời gian thực trên Orange Pi 5.

        Pipeline:
        1. AudioTransport thu âm từ mic (es8388)
        2. Faster-Whisper STT (local, offline)
        3. RAG Engine xử lý câu hỏi
        4. Piper TTS sinh audio
        5. AudioTransport phát qua loa (es8388)
        """
        setup_logging()

        logger.info("=" * 60)
        logger.info("🌱 Mầm Nhỏ — Real-time Voice Pipeline")
        logger.info(f"🎤 Input device: {self._settings.audio_input_device_index}")
        logger.info(f"🔊 Output device: {self._settings.audio_output_device_index}")
        logger.info("=" * 60)

        # Phát lời chào
        greeting = "Chào Mẹ, Mầm Nhỏ đã sẵn sàng lắng nghe."
        self._memory.add_user_message("Xin chào")
        self._memory.add_assistant_message(
            "Chào Mẹ, em là Mầm Nhỏ, trợ lý sản khoa AI. Em rất vui được hỗ trợ Mẹ ạ."
        )

        greeting_audio = self._tts.synthesize(greeting)
        if greeting_audio:
            self._audio.play_wav_bytes(greeting_audio)

        print("\n✅ Pipeline sẵn sàng! Đang lắng nghe...")
        print("   Nhấn Ctrl+C để thoát\n")

        while True:
            try:
                # Step 1: Thu âm
                print("🎤 Đang lắng nghe...")
                wav_path = self._audio.record_to_file(
                    duration=30.0,
                    silence_timeout=self._settings.audio_silence_timeout,
                    silence_threshold=self._settings.audio_silence_threshold,
                )

                # Step 2: STT
                print("⏳ Đang nhận diện giọng nói...")
                with Timer("STT", log_level="INFO"):
                    user_text = self._stt.transcribe(wav_path)

                # Dọn file tạm
                try:
                    os.remove(wav_path)
                except OSError:
                    pass

                if not user_text.strip():
                    print("  ⚠️ Không nghe rõ, đang lắng nghe lại...\n")
                    continue

                print(f"🗣️ Mẹ: {user_text}")

                # Step 3: RAG
                print("🧠 Đang suy nghĩ...")
                with Timer("RAG pipeline", log_level="INFO"):
                    response, safety = self._rag.process_query(
                        user_input=user_text,
                        memory=self._memory,
                        trimester=self._trimester,
                    )

                if safety and safety.is_emergency:
                    print("🚨 [CẢNH BÁO KHẨN CẤP]")

                # Step 4: TTS + Playback
                print(f"🌱 Mầm Nhỏ: {response}")
                with Timer("TTS + Playback", log_level="INFO"):
                    audio_bytes = self._tts.synthesize(response)
                    if audio_bytes:
                        self._audio.play_wav_bytes(audio_bytes)

                print(f"  [RAM: {get_memory_usage_mb():.1f}MB | "
                      f"Memory: {self._memory.turn_count} turns]\n")

            except KeyboardInterrupt:
                print("\n\nTạm biệt Mẹ! 🌱")
                break
            except Exception as e:
                logger.error(f"Pipeline error: {e}")
                print(f"❌ Lỗi: {e}\n")

        # Cleanup
        self._audio.close()

    def run_interactive(self) -> None:
        """
        Run an interactive text-based conversation loop.

        Useful for testing the RAG pipeline without audio hardware.
        Type 'quit' or 'exit' to stop.
        """
        setup_logging()
        logger.info("=" * 60)
        logger.info("🌱 Mầm Nhỏ — Interactive Mode (Text)")
        logger.info("=" * 60)
        logger.info("Type 'quit' to exit, 'reset' to clear memory")
        logger.info(f"RAM usage: {get_memory_usage_mb():.1f}MB")
        logger.info("")

        while True:
            try:
                user_input = input("\n🤰 Mẹ: ").strip()
            except (EOFError, KeyboardInterrupt):
                break

            if not user_input:
                continue
            if user_input.lower() in ("quit", "exit", "thoát"):
                break
            if user_input.lower() in ("reset", "xóa"):
                self.reset_session()
                print("  [Đã xóa bộ nhớ hội thoại]")
                continue

            response, safety = self._rag.process_query(
                user_input=user_input,
                memory=self._memory,
                trimester=self._trimester,
            )

            prefix = "🚨" if safety.is_emergency else "🌱"
            print(f"\n{prefix} Mầm Nhỏ: {response}")
            print(f"  [RAM: {get_memory_usage_mb():.1f}MB | "
                  f"Memory: {self._memory.turn_count} turns]")


# ── Entry Point ──────────────────────────────

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Mầm Nhỏ Voice Pipeline")
    parser.add_argument(
        "--voice", action="store_true",
        help="Chạy voice loop thời gian thực (mic → STT → RAG → TTS → speaker)"
    )
    args = parser.parse_args()

    pipeline = VoicePipeline()

    if args.voice:
        pipeline.run_voice_loop()
    else:
        pipeline.run_interactive()
